### ISSUE TITLE
Apply all checkstyle checks

### ISSUE THREAD

**Issue by MEZk** [DataMinerOpenSource/dMiner#21]
We should uncomment all checkstyle-checks in checkstyle_checks.xml and resolve all violations.

**Comment by Vladlis** [comment]
I'm not sure whether we need RequireThisCheck, reason: https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L357

**Comment by MEZk** [comment]
@Vladlis 
Agree.
